config/routes.rb
Rails.application.routes.draw do

  mount CoreAPI => '/'
  mount GrapeSwaggerRails::Engine => '/swagger'
  
  scope :admin do
    root 'dashboards#index'
    devise_for :users, controllers: { sessions: 'users/sessions'}
    resources :users
    resources :beers do
      put 'archive', on: :member
      put 'unarchive', on: :member
    end
    resources :categories
  end  
  

  get '/',  to: redirect('/swagger')

end

app/views/shares/_header.html.erb
<ul class="nav navbar-top-links navbar-right">
    <% if user_signed_in? %>
        <li><%= current_user.email %></li>
    <% end %>
    <!-- /.dropdown -->
    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
        </a>
        <ul class="dropdown-menu dropdown-user">
            <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
            </li>
            <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
            </li>
            <li class="divider"></li>
            <li>
                <%= link_to( destroy_user_session_path, :method => :delete) do %> 
                    <i class="fa fa-sign-out fa-fw"></i>
                    Logout
                <% end %>
            </li>
        </ul>
        <!-- /.dropdown-user -->
    </li>
    <!-- /.dropdown -->
</ul>

app/views/shares/_sidebar.html.erb
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
            <li class="sidebar-search">
                <div class="input-group custom-search-form">
                    <input type="text" class="form-control" placeholder="Search...">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
                </div>
                <!-- /input-group -->
            </li>
            <li>
                <%= link_to categories_path do %>
                    <i class="fa fa-table fa-fw"></i>
                    Categories
                <% end %>
            </li>
            <li>
                <%= link_to beers_path do %>
                    <i class="fa fa-edit fa-fw"></i>
                    Beers
                <% end %>
            </li>
            <li>
                <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Admin Members<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <%= link_to "List", users_path %>
                    </li>
                    <li>
                        <%= link_to "Add new", new_user_path %>
                    </li>
                </ul>
                <!-- /.nav-second-level -->
            </li>
        </ul>
    </div>
    <!-- /.sidebar-collapse -->
</div>
<!-- /.navbar-static-side -->