config/routes.rb
Rails.application.routes.draw do

  mount CoreAPI => '/'
  mount GrapeSwaggerRails::Engine => '/swagger'
  
  scope :admin do
    root 'dashboards#index'
    devise_for :users, controllers: { sessions: 'users/sessions'}
    resources :users
    resources :beers do
      put 'archive', on: :member
      put 'unarchive', on: :member
    end
    resources :categories
  end  
  

  get '/',  to: redirect('/swagger')

end

app/models/user.rb
class User < ActiveRecord::Base
  paginates_per 10

  acts_as_paranoid

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
  #:registerable

  validates :name, presence: true
  validates :address, presence: true
  validates :email, presence: true, uniqueness: true

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  layout false
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.page params[:page]
  end

  # GET /users/1
  def show
    respond_to do |format|
      format.js
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)
    #to do for generate pass and send mail
    if @user.save
      redirect_to users_url, notice: 'Member was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to users_url, notice: 'Member was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'Member was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      permited_params = params.require(:user).permit(:name, :email, :address)
      permited_params.merge!(password: '12345678')
    end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <ul class="alert alert-danger">
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control"%>
  </div>

  <div class="form-group">
  <%= f.label :email %>
  <%= f.text_field :email, class: "form-control"%>
  </div>

  <div class="form-group">
  <%= f.label :address %>
  <%= f.text_field :address, class: "form-control"%>
  </div>

  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/_modal_show.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title" id="myModalLabel"></h4>
            </div>
            <div class="modal-body">
                <table>
                    <tbody>
                        <tr>
                            <td><strong>Email:&nbsp;</strong></td>
                            <td id='email'></td>
                        </tr>
                        <tr>
                            <td  colspan="3">
                                <strong> Address: </strong>
                                <p id="address"></p>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

app/views/users/_user.html.erb
<tr>
  <td><%= user.id %></td>
  <td><%= user.try(:name) %></td>
  <td><%= user.try(:email) %></td>
  <td><%= truncate user.try(:address), length: 160 %></td>
  <td>
    <%= link_to "Show", user, :class => "", :remote => true, "data-toggle" => "modal", "data-target" => "#myModal" %> |
    <%= link_to 'Edit', edit_user_path(user) %> |
    <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %>
  </td>
</tr>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="page-header" >Listing Admin Members</h1>

<% if notice %>
  <div class="alert alert-success"><%= notice %></div>
<% end %>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Table
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>
                                <th class="col-lg-1 text-center" >#</th>
                                <th class="col-lg-2 text-center">Name</th>
                                <th class="col-lg-3 text-center">Email</th>
                                <th class="col-lg-4 text-center">Address</th>
                                <th class="col-lg-2 text-center">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                          <%= render partial: "user", collection: @users %>
                        </tbody>
                    </table>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
</div>

<div id="category-modal">
    <%= render "modal_show" %>
</div>

<div class="row">
    <div class="pull-left">
        <div class="text-center">
            <%= paginate @users %>
        </div>
    </div>
    <div class="pull-right pagination">
    <%= link_to 'New User', new_user_path, class: "btn btn-default"%>
    </div>
</div>

app/views/users/new.html.erb
<h1 class="page-header" >New User</h1>

<%= render 'form' %>

app/views/users/show.js.erb
$("#category-modal .modal-title").html("<%= @user.name %>");
$("#category-modal .modal-body #email").html("<%= @user.email %>");
$("#category-modal .modal-body #address").html("<%= @user.address %>");