config/routes.rb
Rails.application.routes.draw do

  mount CoreAPI => '/'
  mount GrapeSwaggerRails::Engine => '/swagger'
  
  scope :admin do
    root 'dashboards#index'
    devise_for :users, controllers: { sessions: 'users/sessions'}
    resources :users
    resources :beers do
      put 'archive', on: :member
      put 'unarchive', on: :member
    end
    resources :categories
  end  
  

  get '/',  to: redirect('/swagger')

end

app/models/beer.rb
class Beer < ActiveRecord::Base
  paginates_per 10

  acts_as_paranoid

  belongs_to :category

  validates :name, presence: true
  validates :category_id, presence: true
  validates :manufacturer, presence: true
  validates :country, presence: true
  validates :price, presence: true, format: { :with => /\A\d+(?:\.\d{0,2})?\z/ }, numericality: {:greater_than => 0}
  validates :description, presence: true

  scope :beers_of_category, ->(category_id) { where(category_id: category_id) }
  scope :archived, ->{ where( archive_status: 1) }
  scope :unarchived, ->{ where( archive_status: 0) }
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_action :set_beer, only: [:show, :edit, :update, :destroy, :archive, :unarchive]
  before_action :get_categories, only: [:new, :edit, :create, :update]

  # GET /beers
  def index
    @beers = Beer.order(id: :desc).page params[:page]
  end

  # GET /beers/1
  def show
    respond_to do |format|
      format.js
    end
  end

  # GET /beers/new
  def new
    @beer = Beer.new
  end

  # GET /beers/1/edit
  def edit
  end

  # POST /beers
  def create
    @beer = Beer.new(beer_params)
    if @beer.save
      redirect_to beers_url, notice: 'Beer was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /beers/1
  def update
    if @beer.update(beer_params)
      redirect_to beers_url, notice: 'Beer was successfully updated.' 
    else
      render :edit
    end
  end

  # DELETE /beers/1
  def destroy
    @beer.destroy
    redirect_to beers_url, notice: 'Beer was successfully destroyed.'
  end

  #PUT beers/1/archive
  def archive
    if @beer.update(archive_status: 1)
      redirect_to :back, notice: 'Beer was successfully archived.' 
    else
      redirect_to beers_url, notice: 'Beer was not successfully archived.' 
    end
  end

   #PUT beers/1/unarchive
  def unarchive
    if @beer.update(archive_status: 0)
      redirect_to :back, notice: 'Beer was successfully unarchived.' 
    else
      redirect_to beers_url, notice: 'Beer was not successfully unarchived.' 
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer
      @beer = Beer.includes(:category).find(params[:id])
    end

    def get_categories
      @categories = Category.pluck(:name, :id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beer_params
      permited_params = params.require(:beer).permit(:name, :manufacturer, :country, :price, :description)
      permited_params.merge!(category: Category.find_by(id: params[:beer][:category_id]))
    end
end

app/views/beers/_beer.html.erb
<tr>
  <td><%= beer.id %></td>
  <td><%= beer.name %></td>
  <td><%= beer.manufacturer %></td>
  <td><%= beer.country %></td>
  <td><%= beer.price ? number_to_currency(beer.price, :precision => 2) : number_to_currency(0) %></td>
  <td>
    <%= link_to "Show", beer, :class => "", :remote => true, "data-toggle" => "modal", "data-target" => "#myModal" %> |
    <%= link_to 'Edit', edit_beer_path(beer) %> |
    <%=
    if beer.archive_status == 1
      link_to 'Unarchive', unarchive_beer_path(beer), method: :put, data: { confirm: 'Are you sure, you wanna unarchive this beer?' }
    else
      link_to 'Archive', archive_beer_path(beer), method: :put, data: { confirm: 'Are you sure, you wanna archive this beer?' }
    end
    %> |
    <%= link_to 'Destroy', beer, method: :delete, data: { confirm: 'Are you sure?' } %>
  </td>
</tr>

app/views/beers/_form.html.erb
<%= form_for(@beer) do |f| %>
  <% if @beer.errors.any? %>
    <div id="error_explanation">
      <ul class="alert alert-danger">
      <% @beer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control"%>
  </div>

  <div class="form-group">
  <%= f.label :category %>
  <%= f.select :category_id, @categories ,{include_blank: true}, {class: "form-control"}%>
  </div>

  <div class="form-group">
  <%= f.label :manufacturer %>
  <%= f.text_field :manufacturer, class: "form-control"%>
  </div>

  <div class="form-group">
  <%= f.label :country %>
  <%= f.text_field :country, class: "form-control"%>
  </div>

  <div class="form-group">
  <%= f.label :price %>
  <%= f.number_field :price, class: "form-control", :step => 'any'%>
  </div>

  <div class="form-group">
  <%= f.label :description %>
  <%= f.text_area :description, class: "form-control", rows: "5" %>
  </div>

  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/beers/_modal_show.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title" id="myModalLabel"></h4>
            </div>
            <div class="modal-body">
                <table>
                    <tbody>
                        <tr>
                            <td><strong>Category:&nbsp;</strong></td>
                            <td id='category'></td>
                        </tr>
                        <tr>
                            <td><strong>Country:&nbsp;</strong></td>
                            <td id='country'></td>
                        </tr>
                        <tr>
                            <td><strong>Manufacturer:&nbsp;</strong></td>
                            <td id='manufacturer'></td>
                        </tr>
                        <tr>
                            <td ><strong>Price:&nbsp;</strong></td>
                            <td id='price'></td>
                        </tr>
                        <tr>
                            <td  colspan="3">
                                <strong> Description: </strong>
                                <p id="description"></p>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

app/views/beers/edit.html.erb
<h1>Editing Beer</h1>

<%= render 'form' %>

app/views/beers/index.html.erb
<h1 class="page-header"> Listing Beers</h1>

<% if notice %>
  <div class="alert alert-success"><%= notice %></div>
<% end %>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Table
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>
                                <th class="col-lg-1 text-center" >#</th>
                                <th class="col-lg-2 text-center">Name</th>
                                <th class="col-lg-2 text-center">Manufacturer</th>
                                <th class="col-lg-2 text-center">Country</th>
                                <th class="col-lg-1 text-center">Price</th>
                                <th class="col-lg-3 text-center">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                          <%= render partial: "beer", collection: @beers %>
                        </tbody>
                    </table>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
</div>

<div id="category-modal">
    <%= render "modal_show" %>
</div>

<div class="row">
    <div class="pull-left">
        <div class="text-center">
            <%= paginate @beers %>
        </div>
    </div>
    <div class="pull-right pagination">
        <%= link_to 'New Beer', new_beer_path, class: "btn btn-default" %>
    </div>
</div>

app/views/beers/new.html.erb
<h1 class="page-header">New Beer</h1>

<%= render 'form' %>

app/views/beers/show.js.erb
$("#category-modal .modal-title").html("<%= @beer.name %>");
$("#category-modal .modal-body #country").html("<%= @beer.country %>");
$("#category-modal .modal-body #manufacturer").html("<%= @beer.manufacturer %>");
$("#category-modal .modal-body #price").html("<%= @beer.price ? number_to_currency(@beer.price, :precision => 2) : number_to_currency(0) %>");
$("#category-modal .modal-body #category").html("<%= @beer.category.name %>");
$("#category-modal .modal-body #description").html("<%= @beer.description %>");