config/routes.rb
Rails.application.routes.draw do

  mount CoreAPI => '/'
  mount GrapeSwaggerRails::Engine => '/swagger'
  
  scope :admin do
    root 'dashboards#index'
    devise_for :users, controllers: { sessions: 'users/sessions'}
    resources :users
    resources :beers do
      put 'archive', on: :member
      put 'unarchive', on: :member
    end
    resources :categories
  end  
  

  get '/',  to: redirect('/swagger')

end

app/models/category.rb
class Category < ActiveRecord::Base
  paginates_per 10

  acts_as_paranoid

  has_many :beers, dependent: :restrict_with_error

  has_many :unarchived_beers, -> { where archive_status: 0 }, class_name: 'Beer'

  validates :name, presence: true
  validates :description, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  def index
    @categories = Category.order(id: :desc).page params[:page]
  end

  # GET /categories/1
  def show
    respond_to do |format|
      format.js
    end
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_url, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /categories/1
  def update
    if @category.update(category_params)
      redirect_to categories_url, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /categories/1
  def destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.' if @category.destroy
    redirect_to categories_url, notice: 'Cannot delete record because of `dependent beers'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/views/categories/_category.html.erb
<tr>
  <td><%= category.id %></td>
  <td><%= category.name %></td>
  <td><%= truncate category.description, length: 160 %></td>
  <td>
    <%= link_to "Show", category, :class => "", :remote => true, "data-toggle" => "modal", "data-target" => "#myModal" %> |
    <%= link_to 'Edit', edit_category_path(category) %> |
    <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %>
  </td>
</tr>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>

  <% if @category.errors.any? %>
    <div id="error_explanation">
      <ul class="alert alert-danger">
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>

    </div>
  <% end %>

  <div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control"%>
  </div>

  <div class="form-group">
  <%= f.label :description %>
  <%= f.text_area :description, class: "form-control", rows: "5" %>
  </div>

  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/categories/_modal_show.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title" id="myModalLabel"></h4>
            </div>
            <div class="modal-body"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

app/views/categories/edit.html.erb
<h1 class="page-header">Editing Category</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 class="page-header"> Listing Categories</h1>

<% if notice %>
  <div class="alert alert-success"><%= notice %></div>
<% end %>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Table
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>
                                <th class="col-lg-1 text-center" >#</th>
                                <th class="col-lg-3 text-center">Name</th>
                                <th class="col-lg-6 text-center">Description</th>
                                <th class="col-lg-2 text-center">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                          <%= render partial: "category", collection: @categories %>
                        </tbody>
                    </table>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
</div>

<div id="category-modal">
    <%= render "modal_show" %>
</div>

<div class="row">
    <div class="pull-left">
        <div class="text-center">
            <%= paginate @categories %>
        </div>
    </div>
    <div class="pull-right pagination">
        <%= link_to 'New Category', new_category_path, class: "btn btn-default" %>
    </div>
</div>

app/views/categories/new.html.erb
<h1 class="page-header"> New Category</h1>

<%= render 'form' %>

app/views/categories/show.js.erb
$("#category-modal .modal-title").html("<%= @category.name %>");
$("#category-modal .modal-body").html("<%= @category.description %>");